# Get editor completions based on the config schema
'$schema' = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$hostname\
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$line_break\
$character"""

[character]
format = '[┗━ ⟶](bold yellow) '

[hostname]
format   = '[$hostname]($style)'
ssh_only = false
style    = 'bold blue'

[username]
format      = '[\[](bold)[$user](bold red)[\]](bold) in '
show_always = true

[directory]
format            = '[$path]($style) '
style             = 'bold yellow'
truncate_to_repo  = false
truncation_length = 2

[git_branch]
format = 'on [$symbol$branch]($style)'
style  = 'bold bright-purple'
symbol = ' '

[git_status]
ahead    = ''
behind   = ''
deleted  = 'x'
diverged = ''
format   = '( [\[](bold bright-purple)[$all_status$ahead_behind](bold)[\]](bold bright-purple)) '
renamed  = 'r'

[nodejs]
format = 'with [$symbol($version )]($style)'
symbol = ' '

[rust]
format = 'with [$symbol($version )]($style)'
style  = 'bold red'
symbol = ' '
